ALTER TABLE jogos DROP CONSTRAINT fk_equipe1;
ALTER TABLE jogos DROP CONSTRAINT fk_equipe2;
ALTER TABLE jogos ADD CONSTRAINT fk_equipe1 FOREIGN KEY(idequipe1) REFERENCES equipes(idequipe) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE jogos ADD CONSTRAINT fk_equipe2 FOREIGN KEY(idequipe2) REFERENCES equipes(idequipe) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE partidas DROP CONSTRAINT fk_equipe1;
ALTER TABLE partidas ADD CONSTRAINT fk_equipe1 FOREIGN KEY (idequipe1, idequipe2) REFERENCES jogos(idequipe1, idequipe2) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE jogadores DROP CONSTRAINT fk_equipe;
ALTER TABLE jogadores ADD CONSTRAINT fk_equipe FOREIGN KEY (idequipe) REFERENCES equipes(idequipe) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE diretores DROP CONSTRAINT fk_equipe;
ALTER TABLE diretores ADD CONSTRAINT fk_equipe FOREIGN KEY (equipe) REFERENCES equipes(idequipe) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE uniformes DROP CONSTRAINT fk_equipe;
ALTER TABLE uniformes ADD CONSTRAINT fk_equipe FOREIGN KEY (equipe) REFERENCES equipes(idequipe) ON DELETE CASCADE ON UPDATE CASCADE;

UPDATE equipes SET idequipe=3 WHERE idequipe=5